### PR TITLE
Linux support, source downloads & installs, help scripts

### PR DESCRIPTION
**Pull request by AZMCode**
What's on the tin

### CODE REVIEW

**Comment by AZMCode** [comment]
@austinbv, any progress on merging?

**Comment by AZMCode** [comment]
Closing, as my fork has become the referred-to repository for the plugin.

**Comment by austinbv** [comment]
Thanks for keeping this alive!

**Comment by AZMCode** [comment]
No problem! I hope to help integrate contributions to this project, for the community and whoever maintains it after me.

**Pull request closed without merging**
